// <auto-generated />
namespace SystemSrodkowTrwalych.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dsad1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dsad1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106221717054_dsad1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
